### PR TITLE
MMCA-4107 : Address/Fix the platOps-pr-bot comments for the repo - 'c…

### PR DESCRIPTION
**Pull request by sameerhmrc**
JIRA Link : https://jira.tools.tax.service.gov.uk/browse/MMCA-4107

### CODE REVIEW

**Comment by tyagikumarvineet** [comment]
Could you please make sure that below (its the last point in the ticket) has been addressed ?

AesGCMCrypto can be used instead of SecureGCMCipher, it's included with your version of bootstrap-play. Remove [app/crypto/EncryptedValue.scala](https://github.com/hmrc/customs-cash-account-frontend/blob/MMCA-4052/app/crypto/EncryptedValue.scala#L40) and replace all occurances - for more details see https://github.com/hmrc/crypto

**Comment by sameerhmrc** [comment]
> Could you please make sure that below (its the last point in the ticket) has been addressed ?
> 
> AesGCMCrypto can be used instead of SecureGCMCipher, it's included with your version of bootstrap-play. Remove [app/crypto/EncryptedValue.scala](https://github.com/hmrc/customs-cash-account-frontend/blob/MMCA-4052/app/crypto/EncryptedValue.scala#L40) and replace all occurances - for more details see https://github.com/hmrc/crypto

The encryption related changes have been captured as part of the story https://jira.tools.tax.service.gov.uk/browse/MMCA-4138

**Comment by tyagikumarvineet** [comment]
@sameerhmrc thanks for the update and could you please have a look as mandatory checks are failing.? Let me know once done, will approve the changes.

**Review by tyagikumarvineet — APPROVED** [review]
Approved

**Comment by sameerhmrc** [comment]
> Approved

thanks

**Pull request merged**
