### PR TITLE
[MMCA-4882] Bugfix: Fixing double headings

### PR DESCRIPTION
**Pull request by wg-hmrc**

### CODE REVIEW

**Comment by tyagikumarvineet** [comment]
Please fix the below scalastyle warnings

[warn] /Users/vineet.tyagi/hmrc/codebase/customs-cash-account-frontend/test/viewmodels/CashAccountV2ViewModelSpec.scala:22: File line length exceeds 160 characters
[warn] /Users/vineet.tyagi/hmrc/codebase/customs-cash-account-frontend/test/views/CashAccountTransactionsNotAvailableSpec.scala:67:0: Whitespace at end of line

**Comment by AdamCoops** [comment]
no issues from, will approve once scalastyles are resolved.

**Comment by AdamCoops** [comment]
You have a few broken tests

[info] *** 7 TESTS FAILED ***
[error] Failed tests:
[error] 	views.CashAccountTransactionsNotAvailableSpec
[error] 	controllers.CashAccountV2ControllerSpec
[error] 	views.CashAccountNoTransactionsWithBalanceSpec
[error] 	controllers.CashAccountControllerSpec

**Comment by tyagikumarvineet** [comment]
> Please fix the below scalastyle warnings
> 
> [warn] /Users/vineet.tyagi/hmrc/codebase/customs-cash-account-frontend/test/viewmodels/CashAccountV2ViewModelSpec.scala:22: File line length exceeds 160 characters [warn] /Users/vineet.tyagi/hmrc/codebase/customs-cash-account-frontend/test/views/CashAccountTransactionsNotAvailableSpec.scala:67:0: Whitespace at end of line

This has been resolved now

**Review by tyagikumarvineet — APPROVED** [review]

**Pull request merged**
